name: Test

on:
  push:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install tools
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3

      - name: Run tests
        run: |
          mise run test
